const DEMO_CHARGES = [
  {
    id: 'demo-1',
    name: 'Netflix',
    amount: 15.49,
    frequency: 'monthly',
    category: 'Entertainment',
    recommendation: 'keep',
    reason: 'Active usage detected — streamed content 18 days this month.',
    icon: '🎬',
    isHidden: false,
  },
  {
    id: 'demo-2',
    name: 'Spotify',
    amount: 9.99,
    frequency: 'monthly',
    category: 'Music',
    recommendation: 'keep',
    reason: 'Daily listening habit across devices. High value per dollar.',
    icon: '🎵',
    isHidden: false,
  },
  {
    id: 'demo-3',
    name: 'Adobe Creative Cloud',
    amount: 54.99,
    frequency: 'monthly',
    category: 'Software',
    recommendation: 'review',
    reason: 'Last login was 47 days ago. Consider pausing until needed.',
    icon: '🎨',
    isHidden: false,
  },
  {
    id: 'demo-4',
    name: 'Planet Fitness',
    amount: 24.99,
    frequency: 'monthly',
    category: 'Health',
    recommendation: 'cancel',
    reason: 'No check-ins recorded in the past 3 months.',
    icon: '💪',
    isHidden: false,
  },
  {
    id: 'demo-5',
    name: 'LinkedIn Premium',
    amount: 39.99,
    frequency: 'monthly',
    category: 'Professional',
    recommendation: 'cancel',
    reason: 'Profile views unchanged. InMail credits unused for 60+ days.',
    icon: '💼',
    isHidden: false,
  },
  {
    id: 'demo-6',
    name: 'iCloud+',
    amount: 2.99,
    frequency: 'monthly',
    category: 'Storage',
    recommendation: 'keep',
    reason: 'Low cost, high utility. 87% of 50 GB used.',
    icon: '☁️',
    isHidden: false,
  },
  {
    id: 'hidden-demo-1',
    name: 'Monthly Maintenance Fee',
    amount: 12.00,
    frequency: 'monthly',
    category: 'Banking',
    recommendation: 'cancel',
    reason: 'Avoidable — maintain a $1,500 minimum balance to waive this fee.',
    icon: '🏦',
    isHidden: true,
  },
  {
    id: 'hidden-demo-2',
    name: 'Overdraft Protection Fee',
    amount: 34.99,
    frequency: 'monthly',
    category: 'Banking',
    recommendation: 'cancel',
    reason: 'Charged twice this month. Linking a savings account removes this fee.',
    icon: '⚠️',
    isHidden: true,
  },
];

export default DEMO_CHARGES;
